### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JimmyPowell** [ChatGPTNextWeb/ChatGPT-Next-Web#4137] opened 2024-02-26 11:12 UTC
### Bug Description

桌面版客户端webdav同步存在问题

### Steps to Reproduce

我设置了webdav的服务器地址、用户名和密码，然后点击检查可用性，桌面版的一直提示错误，但是网页版的没有问题，可以正常备份。

### Expected Behavior

请求帮助

### Deployment Method

- [x] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

win 11

### Additional Logs

桌面版版本：2.11.2
网页端版本：2.10.3

**Comment by H0llyW00dzZ** [comment] 2024-02-26 11:27
I've been knowing it, anyways for @fred-bf whoever owner this repo, it's better to focusing fix a bug, and improve the performance instead of adding another ai especially unstable ai lmao, like previous owner @Yidadaa

**Comment by fredliang44** [comment] 2024-02-26 14:49
@H0llyW00dzZ 
1. Ollama is currently the most requested feature, and it makes a lot of sense to allow more people to use almost all open-source models supported by Ollama. Regarding the stability issues with Ollama, it largely depends on the user's local service and the models themselves. It's worth noting that several companies have already deployed and used it in production environments.

2. The focus of the open-source community is on collaborative efforts and project maintenance. Working together, we can better address issues and, more often than not, this collaboration is driven by shared interests. It's crucial not to prioritize personal preferences in blaming others for how issues are addressed. If you have the time to assist in resolving issues that impact your usage, your contribution would be greatly appreciated.

3. Reproducing and addressing issues of different nature takes time, and it doesn't mean all issues must be resolved before introducing new features to the project.

**Comment by fred-bf** [comment] 2024-02-26 18:10
@H0llyW00dzZ Some of the discussion here has gone off topic. I'll address the question regarding this area. Due to bandwidth constraints, we prioritize merging PRs that can be quickly reviewed. For PRs with broader implications, we gradually conduct thorough testing before merging.

**Comment by JimmyPowell** [comment] 2024-02-26 23:36
@H0llyW00dzZ  @fred-bf
 Thank you all for your efforts and attention to this issue. I've noted the discussion around the project's direction and feature implementation, but I would like to re-emphasize the WebDAV synchronization concern. I understand that resources in open-source projects are limited, and everyone's contributions are based on a love for the community and selfless donation of personal time.

If possible, I hope my issue could receive further attention. I believe this would not only assist me but could also be beneficial to other users who may face similar challenges. If there is any way I can help with diagnosing the issue, or if more information is needed from my side, please let me know.

At the same time, I am open to the project's future developments and look forward to the introduction of new features and improvements. I understand that this may take time, and that the introduction of each new feature needs to balance stability with innovation.

Thank you once again for everyone's hard work and support.

**Comment by H0llyW00dzZ** [comment] 2024-02-27 01:30
> @H0llyW00dzZ @fred-bf Thank you all for your efforts and attention to this issue. I've noted the discussion around the project's direction and feature implementation, but I would like to re-emphasize the WebDAV synchronization concern. I understand that resources in open-source projects are limited, and everyone's contributions are based on a love for the community and selfless donation of personal time.
> 
> If possible, I hope my issue could receive further attention. I believe this would not only assist me but could also be beneficial to other users who may face similar challenges. If there is any way I can help with diagnosing the issue, or if more information is needed from my side, please let me know.
> 
> At the same time, I am open to the project's future developments and look forward to the introduction of new features and improvements. I understand that this may take time, and that the introduction of each new feature needs to balance stability with innovation.
> 
> Thank you once again for everyone's hard work and support.

Anyways

I might made my own synchronization solution, written in Go later, instead of fixing bugs in `WebDAV`. This is because `WebDAV` is quite outdated and no longer aligns with modern standards.

**Comment by H0llyW00dzZ** [comment] 2024-02-27 01:31
it's so easy to implement because the data its contain json

**Closed** 2024-09-07 06:34 UTC
Labels: bug
