### ISSUE TITLE
[Bug] 视觉模式回答不完整（回答中断）

### ISSUE THREAD

**Issue by devyujie** [ChatGPTNextWeb/ChatGPT-Next-Web#4084] opened 2024-02-20 11:49 UTC
### Bug Description

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/48620527/ac4288bb-daf7-4fc6-847f-c65fd1086648)

### Steps to Reproduce

。

### Expected Behavior

。

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by QAbot-zh** [comment] 2024-02-21 05:25
+1

**Comment by X-Zero-L** [comment] 2024-02-21 08:05
+1

**Comment by boanz** [comment] 2024-02-22 02:54
+1

**Comment by jam-cc** [comment] 2024-02-23 15:48
@devyujie 请教一下怎么使用视觉模式？在哪里输入图片呢？

**Comment by QAbot-zh** [comment] 2024-02-23 15:56
> @devyujie 请教一下怎么使用视觉模式？在哪里输入图片呢？

切换成一个支持视觉的模型，比如gpt4v或者gemini-vision，就会出现上传图片的图标

**Comment by KyleJKC** [comment] 2024-02-24 18:50
Same

**Comment by DreamsCat** [comment] 2024-02-26 03:36
same,hot to fix? change max_tokens to 4096,same problean

**Comment by H0llyW00dzZ** [comment] 2024-02-26 04:25
you need to use `max_tokens` for `gpt-4-vision-preview`

example:

https://hackerchat.btz.sh/

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/8124bc2a-86db-4952-8979-bae4ff99aa62)

**Comment by H0llyW00dzZ** [comment] 2024-02-26 04:27
> same,hot to fix? change max_tokens to 4096,same problean

it doesn't work because default on this repository has been disabled it

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/client/platforms/openai.ts#L109

**Comment by H0llyW00dzZ** [comment] 2024-02-26 12:16
Anyways This bug can be easily fixed. However, I don't believe it will be merged into the main branch since the owner has made changes.

**Comment by AndyX-Net** [comment] 2024-02-27 01:23
It's really bad, the problem still reproduce even after updated to version 2.11.2.

**Comment by H0llyW00dzZ** [comment] 2024-02-27 01:25
> > Anyways This bug can be easily fixed. However, I don't believe it will be merged into the main branch since the owner has made changes.
> 
> It's really bad, the problem still reproduce even after updated to version 2.11.2.

Yes, I understand that there's nothing particularly remarkable about the latest version. It would be more beneficial to focus on bug fixes and performance improvements, rather than adding another AI that may not be entirely stable for all users.

**Comment by DreamsCat** [comment] 2024-02-27 01:26
> you need to use `max_tokens` for `gpt-4-vision-preview`
> 
> example:
> 
> https://hackerchat.btz.sh/
> 
> ![image](https://private-user-images.githubusercontent.com/17626300/307663665-8124bc2a-86db-4952-8979-bae4ff99aa62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTczNzcsIm5iZiI6MTcwODk5NzA3NywicGF0aCI6Ii8xNzYyNjMwMC8zMDc2NjM2NjUtODEyNGJjMmEtODZkYi00OTUyLTg5NzktYmFlNGZmOTlhYTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDAxMjQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYzY0MzJhNDM4NzQ4ZDM3Y2I4ZDg2YTFjYTAwNGZjZjg2M2RkMWIyZmU2OTBjYmExOWZhNmIxMjhlMTRmNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YGxUqVShpXoSJuhpVuRLi-ASRlq6VUVJMG9U2ZIiKaE)


thank,but I don't see the use max tokens option...

**Comment by DreamsCat** [comment] 2024-02-27 01:27
> > same,hot to fix? change max_tokens to 4096,same problean
> 
> it doesn't work because default on this repository has been disabled it
> 
> https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/client/platforms/openai.ts#L109

okok，i got it

**Comment by AndyX-Net** [comment] 2024-02-27 01:31
> > > Anyways This bug can be easily fixed. However, I don't believe it will be merged into the main branch since the owner has made changes.
> > 
> > 
> > It's really bad, the problem still reproduce even after updated to version 2.11.2.
> 
> Yes, I understand that there's nothing particularly remarkable about the latest version. It would be more beneficial to focus on bug fixes and performance improvements, rather than adding another AI that may not be entirely stable for everyone.

Agree with your point : )

**Comment by KSnow616** [comment] 2024-02-27 07:54
> > same,hot to fix? change max_tokens to 4096,same problean
> 
> it doesn't work because default on this repository has been disabled it
> 
> https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/client/platforms/openai.ts#L109

Currently GPT4-v has a very low **max_token** default value, which makes the replies very short and imcomplete. Uncommenting the line and build from source again will pass the max_token value again, override the default and solve the problem.

**Comment by fred-bf** [comment] 2024-02-27 09:33
To minimize the impact, only the Vision Model is currently configured separately for max_tokens. If you encounter additional problems, please feel free to give feedback

**Closed** 2024-03-01 09:31 UTC
Labels: bug

**Comment by dustookk** [comment] 2024-08-21 06:43
I just solved the same problem; I hope this can help you guys.

change the code of [isVisionModel](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/ffe32694b0cb2c832337a074e0ef4b277d7db3ee/app/utils.ts#L251) made sure your model name is included
